# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{midas}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Jackson"]
  s.date = %q{2010-05-15}
  s.description = %q{Provides a front end for editing content in a contextual way with WYSIWYG editing}
  s.email = %q{jejacks0n@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.textile",
     "Rakefile",
     "VERSION",
     "generators/midas/midas_generator.rb",
     "lib/midas.rb",
     "midas.gemspec",
     "public/javascripts/midas/editor.js",
     "public/javascripts/midas/midas.js",
     "public/javascripts/midas/toolbar.js",
     "public/javascripts/old_editor.js",
     "public/javascripts/prototype.js",
     "public/stylesheets/midas.css",
     "rails/init.rb",
     "spec/javascripts/editor_spec.js",
     "spec/javascripts/fixtures/fixtures.js",
     "spec/javascripts/fixtures/midas_fixture.html",
     "spec/javascripts/fixtures/midas_styles.css",
     "spec/javascripts/helpers/spec_helper.js",
     "spec/javascripts/integration.html",
     "spec/javascripts/midas_spec.js",
     "spec/javascripts/support/jasmine.yml",
     "spec/javascripts/support/jasmine_config.rb",
     "spec/javascripts/support/jasmine_runner.rb",
     "spec/javascripts/toolbar_spec.js",
     "spec/ruby/helpers/spec_helper.rb",
     "spec/ruby/midas_spec.rb",
     "spec/spec.opts",
     "tasks/midas_tasks.rake"
  ]
  s.homepage = %q{http://github.com/jejacks0n/midas}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A rich text editor gem for Rails}
  s.test_files = [
    "spec/javascripts/support/jasmine_config.rb",
     "spec/javascripts/support/jasmine_runner.rb",
     "spec/ruby/helpers/spec_helper.rb",
     "spec/ruby/midas_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<packr>, [">= 3.1.0"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<jasmine>, [">= 0.10.3.5"])
    else
      s.add_dependency(%q<packr>, [">= 3.1.0"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<jasmine>, [">= 0.10.3.5"])
    end
  else
    s.add_dependency(%q<packr>, [">= 3.1.0"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<jasmine>, [">= 0.10.3.5"])
  end
end

